"""Generate the site's data files from the benchmark.

The site displays corpus figures -- composition counts, relation counts, the
gold branch structure the live engines run on -- and every one of them has to
come from ``benchmark/data/corpus.jsonl`` rather than from a number typed into
the page. A hand-maintained copy drifts the first time an instance is
annotated, and a stale figure on a page shown to reviewers is worse than no
page.

So the data is built, not written::

    python site/build_data.py

Two outputs, from one pass:

``site/data/corpus.js``
    What the page loads. A plain script assigning ``window.SC_CORPUS``, which
    works when the site is opened from the filesystem as well as when it is
    served -- ``fetch`` of a local JSON file is blocked by CORS on ``file://``,
    and a showcase that only works behind a web server is a showcase that
    fails in the room where it matters.

``site/data/corpus.json``
    The same records as plain JSON, for anyone who wants the data rather than
    the page.

Fields are shortened because the whole corpus ships to the browser; the key
map is in ``_FIELDS`` below and mirrored by the readers in ``app.js``.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "benchmark" / "data" / "corpus.jsonl"
OUT = Path(__file__).resolve().parent / "data"

#: Long name -> short key, as read by site/assets/js/app.js.
_FIELDS = {
    "instance_id": "id", "query": "q", "domain": "dom", "construction": "con",
    "separation": "sep", "split": "sp", "gold_conflict_type": "ty",
    "gold_scope_relation": "rel", "passages": "p", "gold_branches": "b",
}


def _attribute(a: dict) -> dict:
    out = {"n": a["name"], "k": a["kind"]}
    if a.get("values"):
        out["v"] = a["values"]
    if a.get("min_value") is not None:
        out["lo"] = a["min_value"]
    if a.get("max_value") is not None:
        out["hi"] = a["max_value"]
    if a.get("boolean_value") is not None:
        out["b"] = a["boolean_value"]
    if a.get("text"):
        out["t"] = a["text"]
    return out


def _branch(b: dict) -> dict:
    app = b["applicability"]
    out = {
        "id": b["branch_id"], "out": b["outcome"], "desc": app["descriptor"],
        "def": bool(app.get("is_default")), "sup": b.get("supporting_passage"),
    }
    if b.get("condition"):
        out["cond"] = b["condition"]
    if app.get("attributes"):
        out["at"] = [_attribute(a) for a in app["attributes"]]
    if b.get("explicitness"):
        out["exp"] = b["explicitness"]
    return out


def _passage(p: dict) -> dict:
    out = {"id": p["id"], "t": p["text"]}
    for long, short in (("source_url", "u"), ("document_id", "d"),
                        ("date", "dt"), ("source_type", "st")):
        if p.get(long):
            out[short] = p[long]
    return out


def _provenance(annotation: dict) -> str:
    """Two classes of evidence, which the paper must never pool.

    The site reports them separately for the same reason the split audit does:
    kappa was measured on double-annotated instances only, and a single figure
    across both classes would misstate the evidence.
    """
    first = (annotation or {}).get("annotator_a")
    return ("two-annotator" if first not in (None, "model-proposed")
            else "model-proposed+adjudicated")


def build() -> list[dict]:
    if not SOURCE.exists():
        raise SystemExit(f"corpus not found: {SOURCE}")

    records = []
    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        rec = {
            "id": row["instance_id"], "q": row["query"], "dom": row["domain"],
            "con": row["construction"], "sep": row.get("separation"),
            "sp": row["split"], "ty": row["gold_conflict_type"],
            "rel": row.get("gold_scope_relation"),
            "prov": _provenance(row.get("annotation")),
            "p": [_passage(p) for p in row["passages"]],
        }
        if row.get("gold_branches"):
            rec["b"] = [_branch(b) for b in row["gold_branches"]]
        if row.get("gold_scoped_answer"):
            rec["sa"] = row["gold_scoped_answer"]
        if row.get("selection_answer"):
            rec["sel"] = row["selection_answer"]
        records.append(rec)
    return records


def main() -> int:
    records = build()
    OUT.mkdir(parents=True, exist_ok=True)
    compact = json.dumps(records, separators=(",", ":"), ensure_ascii=False)

    (OUT / "corpus.json").write_text(compact, encoding="utf-8")
    (OUT / "corpus.js").write_text(
        "/* Generated by site/build_data.py from benchmark/data/corpus.jsonl.\n"
        "   Do not edit by hand -- rebuild instead. */\n"
        "window.SC_CORPUS = " + compact + ";\n",
        encoding="utf-8",
    )

    branches = sum(len(r.get("b", [])) for r in records)
    annotated = sum(1 for r in records if r.get("b"))
    print(f"wrote {len(records)} instances -> site/data/  ({len(compact) / 1024:.0f} KB)")
    print(f"  {annotated} with branch structure, {branches} gold branches")
    for key, label in (("ty", "type"), ("rel", "relation"), ("sp", "split")):
        counts = Counter(r.get(key) for r in records)
        rendered = ", ".join(f"{k or 'none'} {v}" for k, v in sorted(
            counts.items(), key=lambda kv: (-kv[1], str(kv[0]))))
        print(f"  {label}: {rendered}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
